### ISSUE TITLE
Should we mention why it's necessary to develop a in-band protocol solution

### ISSUE THREAD

**Issue by RenjieTang** [mjoras/SCONE-PROTOCL#102]
Given people questioned why SCONEPRO was needed in the first place, I wonder if it's worth it to mention all the out-of-bands solutions don't work well.

**Comment by ihlar** [comment]
Right. It's an interesting question whether the charter should explicitly limit the scope to on-path solutions or if this is something for a working group to resolve. I personally think on-path is the only viable solution, but not sure the charter needs to state that.

**Comment by danwing** [comment]
Yes, explain why it's necessary and explain where https://datatracker.ietf.org/doc/html/draft-brw-sconepro-rate-policy-discovery fails to meet requirements.

**Comment by fluffy** [comment]
@RenjieTang  - I've been struggling to figure out to say this in a one or two sentences. You have any thoughts of what we might add to the charter for this?

**Comment by RenjieTang** [comment]
“Currently there exists no standardized way for a client to fetch
throughput information from a network. Building a dedicated API at CSP
endpoints requires that endpoint to communicate with the traffic shapers
and introduces more complexity.
Building a protocol to communicate such information directly between CAP
and CSP is the simplest solution and thus it should be worked on by IETF.”

Yeah it’s kinda hard to express it concisely. I gave my best shot.

**Comment by ihlar** [comment]
PR #104 proposes a definition of a network device as anything on the path of a UDP 5-tuple that can drop or delay packets. 
I wonder if such a definition is good enough to make it clear that an off-path or API solution is quite impossible.

**Comment by Kevsy** [comment]
>  requires that endpoint to communicate with the traffic shapers
and introduces more complexity.

My mobile-centric view: the most complex aspect for the network is understanding the context of the specific end-user connection , and hence deriving its maximum throughput. 

'Specific' end-user connection is significant, because although end-users in the same cell contend for the same radio resources under congestion, certain end-users will be at cell-edge/indoors/undergoing mobility handover/other signal challenges. The radio network will take account of that when allocating radio resources, and may need to re-transmit radio blocks to those connections, which together typically result in a lower maximum network throughput.

This specific context (and hence maximum network throughput) is derived the same way, regardless of whether that information is subsequently made available in- or  out-of-band. That may or may not require communication with traffic shapers, depending on the network, but it will always require obtaining information on radio conditions.

So although the most complex aspect is the same, two key differences between in- and out-of-band are:

- **Delay**  
  Given the same information source, the techniques involve different network paths, incurring different delay:
   - in-band: network marks packet _en route_ to client, client forwards mark to server
   - out-of-band: server queries network API, which may include round-trips  for authentication and authorisation, as well as the propagation delay to the network API server and back
   - There may be other factors in the difference (e.g. compute resources, use of timer-based caches, availability of near-real-time interfaces) but round-trips and network path are likely to be the most significant.
 
- **Privacy**
  - The in-band technique has implicit knowledge of (at least one) end-user network identifier. It can use that to derive information for a given end-user's connection context. 
  - To achieve the same end-user-specific functionality with out-of-band, any API call would need to source and pass the network identifier, which is typically sensitive and protected (e.g. the end-user's phone number) - thus adding complexity and additional delay (e.g. round-trips to determine/provide end-user consent)

I believe each have pros and cons, and would fit different scenarios- and CAMARA are working on the out-of-band [ConnectivityInsights](https://github.com/camaraproject/ConnectivityInsights) API in parallel.

> Building a protocol to communicate such information directly between CAP
and CSP **is the simplest solution** and thus it should be worked on by IETF

(my highlight) 

I think that's difficult to prove, could rather say 'Building a protocol to communicate such information directly in-band between CAP and CSP complements out-of-band APIs, and should reduce the time to relay the information - an important consideration in volatile radio networks".

**Comment by fluffy** [comment]
OK - I think the merged PR helped clarify where the group is on this. I am going close this issue for now and we can all look at the new charter and see if something needs to be reopened.
