### ISSUE TITLE
Make network-to-client a top-level property of the charter

### ISSUE THREAD

**Issue by tfpauly** [mjoras/SCONE-PROTOCL#15]
The proposed charter currently lists "on-path" as a property of the protocol. This does give network-to-client communication as the example here, but since some initial discussions also included on-path communication from networks to content servers, I would like to see a top-level property to limit scope to network-to-client communication.

**Comment by SpencerDawkins** [comment]
I agree with @tfpauly, on two things:

- If we can limit the scope to "network to client", that would help us deliver something useful for that usage sooner
- I'm almost certain that including "client to network" in the same BOF request and BOF will make it less likely that we can charter something to address either usage (see "fate sharing", which is also true for IETF new work proposals). 

I should ask a related question - do people who want to communicate hints in each direction using the same protocol? 

It seems obvious to me that at least some information being communicated only makes sense in one direction. If there's no overlap, and if the deliverables are organized so that the base protocol for information communication and the description of the information being communicated from network to client are in two different specifications, that would allow people who want to use SCONEPRO to do something other than "network-assisted video optimization through self-adaptation", a phrase used in #14.

**Comment by SpencerDawkins** [comment]
Are we saying that "client-initiated" means that we're not looking at server-to-network? ("is this a SCONEPRO CLIENT or a SCONEPRO ENDPOINT?)

**Comment by Kevsy** [comment]
@tfpauly please could you expand on the reason for not having network-server in scope? I could see that being of use in uplink sessions - e.g. live video upload from cellular clients over 5G (so client-network-server). In this case, if network-server is out of scope, any network hints regarding e.g. congestion, low-throughput radio band, etc.  would only be added to the downlink, i.e. after the first packets had been uploaded. But I suspect there are disadvantages to network-server that outweigh that... thanks!

**Comment by tfpauly** [comment]
Mainly that the solution space is very different (so this proposed charter should pick one side of the network to communicate with), but also that having the network and server try to communicate about specific clients without the clients knowing leads to many more privacy violations.

**Comment by Kevsy** [comment]
Thanks, understood!

**Comment by SpencerDawkins** [comment]
@SpencerDawkins needs to update the PR based on this discussion
