### ISSUE TITLE
 information shared to the network: what and how?

### ISSUE THREAD

**Issue by zaheduzzaman** [mjoras/SCONE-PROTOCL#16]
https://github.com/mjoras/SCONE-PROTOCL/blob/6a75726a973abbd2670ce5f644d82041c64d4dad/documents/charter.md?plain=1#L7

it says - "an on-path protocol for securely communicating network properties to clients relevant to a given application".

All of the considerations so far given to network to client communication. So, how does the network understand which client has which application? an solution to that would be necessary, is that within the scope?

**Comment by SpencerDawkins** [comment]
This is related to issue #11, and discussion is happening in PR #14.

**Comment by SpencerDawkins** [comment]
I think this is also related to #5 - @ihlar, we should talk!

**Comment by SpencerDawkins** [comment]
In discussions, @atiwariphd thinks this is a question about an association. Is that right?

**Comment by anooptomar29** [comment]
This is applicable for video streaming flow . This issue is addressed by issue#28 i.e the communication channel is client initiated. So client (using video streaming flow) would indicate to the n/w that it wants to use SCONE service by initiating a communication channel. Since it is on-path mechanism there is no additional association needs to be established.  "What" part will be addressed as part of detailed protocol definition.

**Comment by anooptomar29** [comment]
Close by #28

**Comment by anooptomar29** [comment]
close by #28
