### ISSUE TITLE
What other groups need coordination

### ISSUE THREAD

**Issue by martinthomson** [mjoras/SCONE-PROTOCL#18]
QUIC ? HTTP ? WebRTC ?  W3C (#17) ?

The charter should list those groups that will need to be consulted about solutions.

**Comment by SpencerDawkins** [comment]
@martinthomson - thank you for asking the question. I agree that these relationships should be named in the charter, especially since these groups should notice if/when a SCONEPRO charter goes to the IETF community for review ("WG Review"), and to groups outside the IETF for review ("External Review"). 

@martinthomson's suggestions are a great start. I agree with QUIC, HTTPbis, and RTCWeb (in the IETF, which coordinates with WebRTC in W3C). If we can get specifics on other relevant W3C groups that should be named, that would be fabulous.

Within the IETF, we might also consider MOQ (they target media over QUIC, which includes video), and AVTCORE (they are working on an RTP over QUIC specification, which includes video). 

I don't know whether TSVWG and CCWG should be called out - if some participants from those working groups notice SCONEPRO, that might be enough. 

MOPS OUGHT to be a coordination point. Their focus is media operations, and (from their charter), 

> MOPS provides a venue for both video industry and Internet engineering
experts to engage in discussion of video technology’s requirements of
networking standards, as well as proposals for new uses of IP technology
in video. 

and they routinely get an update from SVTA (most recently at IETF 118, [here](https://datatracker.ietf.org/meeting/118/materials/slides-118-mops-svta-update-00)). In a perfect world, they could help keep us connected to operators who don't routinely wander through the IETF.

**Comment by mirjak** [comment]
I think it is actually not clear yet if and where we need coordination. Not every protocols that uses QUIC or H3 needs tight coordination with those groups; only we want change something about the these base protocols. I don't see that (yet).

**Comment by SpencerDawkins** [comment]
> I think it is actually not clear yet if and where we need coordination. Not every protocols that uses QUIC or H3 needs tight coordination with those groups; only we want change something about the these base protocols. I don't see that (yet).

I agree with @mirjak that we don't have a clear picture yet. I'm mostly thinking about listing candidates, that we consider when we have a better idea what SCONEPRO scope is.

**Comment by martinthomson** [comment]
I'm not suggesting tight coordination, though I would suggest that if this operates outside of the QUIC envelope, then the QUIC WG will want to have something to say about that.  I would double that for RTP (AVTCORE) as that is a protocol that might operate in the same space, outside of the QUIC envelope and it would be unfortunate if this tromped all over what RTP applications plan to use.

**Comment by SpencerDawkins** [comment]
I'll propose text for this, based on minimalism, and then folks can comment.
