### ISSUE TITLE
SCONE is similar looking to SCION

### ISSUE THREAD

**Issue by LPardue** [mjoras/SCONE-PROTOCL#2]
https://en.m.wikipedia.org/wiki/SCION_(Internet_architecture)

No strong feelings from my side, just pointing out a potential source of pain

**Comment by SpencerDawkins** [comment]
Just to add to the fun, [PANRG ](https://datatracker.ietf.org/rg/panrg/about/)has [two active SCION documents](https://datatracker.ietf.org/rg/panrg/documents/). They aren't adopted, but they've been under discussion in PANRG for years, and have even been the subject of PANRG interim meetings. This isn't **immediately** a problem but a couple of things are worth noting. 

- If SCION is in scope for PANRG, it's because it's research, not engineering (see details in [RFC 7418](https://datatracker.ietf.org/doc/rfc7418/)). If SCONE looks too much like SCION, and SCION is research, that will be a problem (at least, at charter time)

- PANRG produced [RFC 9049]( https://datatracker.ietf.org/doc/rfc9049/), explaining deployment obstacles for historical "Path Aware Networking" technologies (IMO, SCONE qualifies as a PAN). We don't need to worry about whether any of these obstacles are still obstacles for SCONE in order to request a BOF, and may not need to worry about that in order to hold a BOF, but it would be a GREAT idea to go through [Section 4](https://datatracker.ietf.org/doc/html/rfc9049#name-summary-of-lessons-learned) as a checklist, because at least some of the lessons seem, at first glance, to apply. (Several of the applicable lessons don't look like they'll be a problem for SCONE, but I'm looking at 4.9. Endpoints Trusting Intermediate Nodes, and 4.10. Intermediate Nodes Trusting Endpoints, with curiosity). 

(It's not that RFC 9049 is a BCP, it's that anyone who knows about RFC 9049 would be curious, and six of the current IESG members balloted Yes or No Objection when it was published, so someone might remember)

On the bright side, I was the editor for RFC 9049, and @britram was a PANRG co-chair when it was published, so the SCONE proponents are well positioned to do that exercise. :relaxed:

And @britram can tell you if I'm completely wrong about any of this.

**Comment by mjoras** [comment]
A related question we need to answer: specifying that SCONE represents engineering work, rather than research work.

**Comment by mirjak** [comment]
SCION proposes a secure routing protocol. This is really different than what we want. But yes there are questions in PANRG that are relevant, however, as Matt said we want to specify a protocol and PANRG is focused on research. Respectively for SCION it not clear yet how and if to standardise a protocol, so they are working on this now in a research group but the goal is there as well to bring something or parts of it into the IETF at some point.

**Comment by britram** [comment]
+1 to @mirjak -- one of the potential applications of SCION is allowing endpoint control of paths selected based on path property metadata, but that is one of them, and SCION is research because it's a much deeper cut into the Internet architecture than sidecar/overlay path awareness.

That said, all the questions raised in 9217 apply to SCONE as well.

**Comment by wesley-eddy** [comment]
It looks like we can close this issue and plan to discuss further on the side, as it seems agreed that it should not impact chartering.

**Comment by LPardue** [comment]
This issue was purely about the visual similarity of the names, nothing more deep than that. We can bikeshed name, without needing to keep this issue open. I support closing.

**Comment by SpencerDawkins** [comment]
I agree, and I want to thank @LPardue for the observation when he opened the issue - it generated good general discussion that resulted in charter text changes.
