### ISSUE TITLE
To TCP or not to TCP

### ISSUE THREAD

**Issue by mjoras** [mjoras/SCONE-PROTOCL#8]
More generally, should the charter discuss non-QUIC protocols, or leave the door open to such a mechanism to be used with non-QUIC application protocols?

**Comment by SpencerDawkins** [comment]
Charter would be for QUIC initially, with support for other protocols deferred to later work.

**Comment by ihlar** [comment]
Agree to limiting scope to QUIC initially (or indefinitely).

**Comment by SpencerDawkins** [comment]
> Agree to limiting scope to QUIC initially (or indefinitely).

I do, too. I should ask the broader question. _**Who would ONLY use SCONEPRO with TCP (or some other non-QUIC protocol)?**_ 

In our most recent BOF planning call, we said Netflix will probably stay on TCP, rather than moving to QUIC, for the foreseeable future. Is there anyone **else** we can think of, who is in this category?

The model I'm thinking of, is that we said you can't do HTTP/3 over TCP. Obviously, someone can code that up, but we didn't limit HTTP/3 to only things that work over QUIC **and TCP**.

**Comment by Kevsy** [comment]
IME (one network operator, albeit several countries) the network-traffic-shaping of QUIC / UDP is far less prevalent than 'TCP optimisers'. So that may be a consideration  for any goal of making traffic-shaping more transparent.

**Comment by SpencerDawkins** [comment]
@Kevsy - I'm not an operator, but your understanding matches mine. 

Herein begins my rant. 

My understanding (as of the [MARNEW IAB workshop in 2015](https://datatracker.ietf.org/doc/rfc8462/)) was that we couldn't count on operators to turn off TCP optimizers, because operators (in turn) weren't sure what would happen if they DID turn off TCP optimizers in their networks, and we couldn't (at that time) identify people who built TCP optimizers to tell us how their boxes worked, because that was their IPR and (at least in their minds) their competitive advantage. 

If one goal for SCONEPRO is to make path characteristics more predictable, improving the consistency of bandwidth estimation and congestion control, saying "and we're going to make it work on network paths that are even more unpredictable, and we don't have obvious ways to find out why those paths are unpredictable" seems like a suboptimal plan.

**Comment by Kevsy** [comment]
> My understanding (as of the [MARNEW IAB workshop in 2015](https://datatracker.ietf.org/doc/rfc8462/)) was that we couldn't count on operators to turn off TCP optimizers, because operators (in turn) weren't sure what would happen if they DID turn off TCP optimizers in their networks,

Indeed, I think I may have helped present that part of MARNEW - and it led to further investigations on more explicit dialogue from network to application e.g. [Mobile Throughput Guidance](https://datatracker.ietf.org/doc/html/draft-flinck-mobile-throughput-guidance) . 

But in general (and this also applies to the #21 Transparency issue) it would be pretty useful for operators to check the extent to which TCP optimisers are still utilised.

**Comment by SpencerDawkins** [comment]
@Kevsy,

> > My understanding (as of the [MARNEW IAB workshop in 2015](https://datatracker.ietf.org/doc/rfc8462/)) was that we couldn't count on operators to turn off TCP optimizers, because operators (in turn) weren't sure what would happen if they DID turn off TCP optimizers in their networks,
> 
> Indeed, I think I may have helped present that part of MARNEW - and it led to further investigations on more explicit dialogue from network to application e.g. [Mobile Throughput Guidance](https://datatracker.ietf.org/doc/html/draft-flinck-mobile-throughput-guidance) .

I thought I remembered that!

> But in general (and this also applies to the #21 Transparency issue) it would be pretty useful for operators to check the extent to which TCP optimisers are still utilised.

Absolutely.

**Comment by SpencerDawkins** [comment]
The main branch of the charter says this: 

> Work to support TCP or other transport protocols may be considered later in the working group, however, these considerations shouldn't distract from support for video over QUIC.

I don't think we need to say more, if we are going to say anything at all. I think we can close this one as completed.
